### ISSUE TITLE
Staging <> Production To-do's

### ISSUE THREAD

**Issue by kvanderslice** [fiftyandfiftyorg/lifestraw-shopify#8]
- [x] Add link-lists for menu, donation, collections etc.
- [x] Add donations product - do not include a sales channel option for this as we do not want it to display on any 'all' products lists
- [x] Enable blog (steps: https://help.shopify.com/en/manual/sell-online/online-store/blogs)
- [x] To add a products to the uikit template page, you'll need to use the products element and then create a linklist via the navigation to determine what products should show up. Whatever you name the linklist is what you'll include in the backend
- [x] Copy all navigation linklists
- [x] Copy all redirects
- [x] Create redirects from lifestraw.com
- [x] Edit collection.liquid for collections.metafields ideal-for-background, and add -image to the string. So it would be ideal-for-background-image
- [x] Add replacements collection to live site, and attach product type of collections to relevant 
products
- [x] Match filtering being pulled from the products for the chemicals, parasites etc.
- [x] Verify Typekit is pulling fonts correctly on live URL
- [x] Add store locator app (bold store locator) & edit the URL (go to apps, and click 'view details') change the url string to /a/store-locator instead of /apps/store-locator **if url is changed from /store-locator to something else, js function looking for the page needs to change
- [x] Install Metafields Master plugin and include all metafields for products & collections
